# Generated by Django 2.1.1 on 2018-10-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_lister', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
